language: python
addons:
  ssh_known_hosts: libc6.org
python:
- '3.5'
cache: pip
install:
- pip install -r requirements.txt
script: fab build
before_install:
- openssl aes-256-cbc -K $encrypted_7ec4d920bbec_key -iv $encrypted_7ec4d920bbec_iv
  -in deploy_key.enc -out deploy_key -d
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_key
- ssh-add $TRAVIS_BUILD_DIR/deploy_key
- fab publish
