language: python
addons:
  ssh_known_hosts: libc6.org
python:
- '2.7'
install:
- pip install -r requirements.txt
script: fab build
before_install:
- openssl aes-256-cbc -K $encrypted_7ec4d920bbec_key -iv $encrypted_7ec4d920bbec_iv
  -in deploy_key.enc -out deploy_key -d
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
- rsync --delete --exclude ".DS_Store" -pthrvz  --rsh="ssh -i $TRAVIS_BUILD_DIR/deploy_rsa -p 22  " output/ www-data@libc6.org:/var/www/libc6.org/public
