language: python
addons:
  ssh_known_hosts: libc6.org
python:
- '3.6'
cache:
  pip: true
  timeout: 86400
timeout: 1000
install:
- pip install -r requirements.txt
script: fab build
before_install:
- openssl aes-256-cbc -K $encrypted_77975071147f_key -iv $encrypted_77975071147f_iv -in libc6.org.enc -out deploy_key -d
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_key
- ssh-add $TRAVIS_BUILD_DIR/deploy_key
- fab publish
